const { padMapId } = require('./paths')

/**
 * Builds Pokémon Essentials PBS `map_metadata.txt` and `map_connections.txt` for exported panels.
 * Assumptions:
 * - Every exported panel becomes its own map, all same tile dimensions (`panelSize`).
 * - Connections are 1-tile aligned between neighboring panels (offset 0).
 */
function buildPokemonEssentialsPbs({ written, title, panelSize }) {
  const safeTitle = title || 'Grasswhistle'
  const size = Number(panelSize) | 0

  // Map id lookup by panel coordinate.
  const idAt = new Map() // key `${x},${y}` -> mapId
  const posAt = new Map() // key `${x},${y}` -> { x, y } in world tiles
  for (const w of written || []) {
    if (!w || w.rmxpRole === 'group_parent') continue
    idAt.set(`${w.x | 0},${w.y | 0}`, w.mapId | 0)
    posAt.set(`${w.x | 0},${w.y | 0}`, { x: (w.x | 0) * size, y: (w.y | 0) * size })
  }

  // --- map_metadata.txt ---
  const metaLines = []
  metaLines.push('# Generated by Grasswhistle')
  metaLines.push('# See the documentation on the wiki to learn how to edit this file.')
  metaLines.push('#-------------------------------')
  for (const w of written || []) {
    if (w.rmxpRole === 'group_parent') continue
    const mapId = w.mapId | 0
    const x = w.x | 0
    const y = w.y | 0
    metaLines.push(`[${padMapId(mapId)}]   # ${safeTitle} (${x},${y})`)
    metaLines.push(`Name = ${safeTitle}`)
    metaLines.push(`ShowArea = true`)
    // Helps Essentials/Town Map tooling; harmless if unused.
    if (size > 0) metaLines.push(`MapSize = 1,1`)
    metaLines.push('#-------------------------------')
  }

  // --- map_connections.txt ---
  // Each undirected edge is written once (using mapId ordering for stability).
  // We split output into:
  // - map_connections.txt: bordering edge connections only (Debug tool overwrites this file)
  // - map_connections_extra.txt: non-bordering coordinate connections (diagonals/corner-only)
  const connLines = []
  connLines.push('# Generated by Grasswhistle')
  connLines.push('# See the documentation on the wiki to learn how to edit this file.')
  connLines.push('#-------------------------------')

  const extraConnLines = []
  extraConnLines.push('# Generated by Grasswhistle')
  extraConnLines.push('# Non-bordering (coordinate) connections; keep separate so Debug tool does not erase them.')
  extraConnLines.push('# See the documentation on the wiki to learn how to edit this file.')
  extraConnLines.push('#-------------------------------')

  function addEdge(aId, aDir, bId, bDir, offset = 0, comment) {
    const a = aId | 0, b = bId | 0
    if (!(a > 0 && b > 0)) return
    if (a === b) return
    // De-dupe: always write from smaller mapId to larger.
    const line = a < b
      ? `${a},${aDir},${offset},${b},${bDir},${offset}`
      : `${b},${bDir},${offset},${a},${aDir},${offset}`
    if (comment) connLines.push(`# ${comment}`)
    connLines.push(line)
  }

  // For each panel, connect east and south neighbors (covers full grid without duplicates).
  const seen = new Set()
  for (const w of written || []) {
    if (w.rmxpRole === 'group_parent') continue
    const x = w.x | 0
    const y = w.y | 0
    const aId = w.mapId | 0

    const eastId = idAt.get(`${x + 1},${y}`)
    if (eastId) {
      const key = `${Math.min(aId, eastId)}-${Math.max(aId, eastId)}-E`
      if (!seen.has(key)) {
        seen.add(key)
        addEdge(aId, 'E', eastId, 'W', 0, `${safeTitle} (${x},${y}) - (${x + 1},${y})`)
      }
    }
    const southId = idAt.get(`${x},${y + 1}`)
    if (southId) {
      const key = `${Math.min(aId, southId)}-${Math.max(aId, southId)}-S`
      if (!seen.has(key)) {
        seen.add(key)
        addEdge(aId, 'S', southId, 'N', 0, `${safeTitle} (${x},${y}) - (${x},${y + 1})`)
      }
    }

    // Diagonal-only touch (corner contact). Essentials allows non-bordering connections using coordinates:
    //   map1,x1,y1,map2,x2,y2
    // where (x1,y1) of map1 is located at (x2,y2) relative to map2.
    // We generate these for diagonal neighbors so they load seamlessly at corner transitions.
    const diagNeighbors = [
      { dx: 1, dy: 1 },
      { dx: -1, dy: 1 },
      { dx: 1, dy: -1 },
      { dx: -1, dy: -1 },
    ]
    for (const d of diagNeighbors) {
      const nx = x + d.dx
      const ny = y + d.dy
      const bId = idAt.get(`${nx},${ny}`)
      if (!bId) continue
      const aPos = posAt.get(`${x},${y}`)
      const bPos = posAt.get(`${nx},${ny}`)
      if (!aPos || !bPos) continue

      const lo = Math.min(aId, bId)
      const hi = Math.max(aId, bId)
      const key = `${lo}-${hi}-D`
      if (seen.has(key)) continue
      seen.add(key)

      // Stable orientation: map1 = hi, map2 = lo (arbitrary but stable).
      const map1 = hi
      const map2 = lo
      const map1Pos = map1 === aId ? aPos : bPos
      const map2Pos = map2 === aId ? aPos : bPos
      const relX = (map1Pos.x - map2Pos.x) | 0
      const relY = (map1Pos.y - map2Pos.y) | 0

      extraConnLines.push(`# ${safeTitle} diagonal (${x},${y}) - (${nx},${ny})`)
      extraConnLines.push(`${map1},0,0,${map2},${relX},${relY}`)
    }
  }

  return {
    mapMetadataTxt: metaLines.join('\n') + '\n',
    mapConnectionsTxt: connLines.join('\n') + '\n',
    mapConnectionsExtraTxt: extraConnLines.join('\n') + '\n',
  }
}

module.exports = { buildPokemonEssentialsPbs }

